#!/usr/bin/env python3
"""Regenerates Docs/AutomationCommands.md and Docs/Components.md from the engine itself
(`basalt help` and `basalt component.types`), so the reference never drifts from the code.

Usage: python3 scripts/generate_docs.py [path/to/basalt]   (default: build/bin/basalt)
"""
import json, os, subprocess, sys

root = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
default = os.path.join(root, "build", "bin", "basalt" + (".exe" if os.name == "nt" else ""))
basalt = sys.argv[1] if len(sys.argv) > 1 else default

def run(command):
    output = subprocess.run([basalt, command], check=True, capture_output=True, text=True).stdout
    response = json.loads(output)
    if not response.get("ok"):
        raise SystemExit(f"basalt {command} failed: {response}")
    return response["result"]

commands = run("help")["commands"]
lines = ["# Automation Commands", "",
         "Generated by `scripts/generate_docs.py` from `basalt help` — do not edit by hand.", "",
         "Every command is available through the `basalt` CLI and the editor's TCP server (127.0.0.1:7420).",
         "See `.claude/skills/basalt-make-game/SKILL.md` for the workflow.",
         "Commands reject parameters they do not list. In a batch, a request with `\"expectError\": \"<text>\"`",
         "succeeds only if its command fails with an error containing `<text>` (used by tests).", ""]
group = None
for command in commands:
    name = command["command"]
    prefix = name.split(".")[0]
    if prefix != group:
        group = prefix
        lines += [f"## {group}", ""]
    lines.append(f"### `{name}`")
    lines.append("")
    lines.append(command["description"])
    if command["params"]:
        lines.append("")
        lines.append("| Parameter | Type / description |")
        lines.append("|-----------|--------------------|")
        for parameter, description in sorted(command["params"].items()):
            lines.append(f"| `{parameter}` | {description} |")
    lines.append("")
with open(os.path.join(root, "Docs", "AutomationCommands.md"), "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(lines) + "\n")

components = run("component.types")["components"]
lines = ["# Components", "",
         "Generated by `scripts/generate_docs.py` from `basalt component.types` — do not edit by hand.", "",
         "Component data is JSON in scene files, prefabs, `component.set` and Lua `GetComponent/SetComponent`.",
         "Vectors are arrays (`[x, y, z]`), colors are RGB(A) arrays in linear space, rotations are Euler degrees,",
         "asset references are project-relative paths (`Assets/...`) or built-in meshes (`builtin://Cube`).", ""]
for component in components:
    core = " (always present)" if component["core"] else ""
    lines.append(f"## {component['name']}{core}")
    lines.append("")
    lines.append("Fields: " + ", ".join(f"`{field}`" for field in component["fields"]))
    lines.append("")
with open(os.path.join(root, "Docs", "Components.md"), "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(lines) + "\n")
print("Docs regenerated.")
